<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class GuruSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $guru = [
            [
                'username' => 'budi_santoso',
                'nama_lengkap' => 'Budi Santoso, S.Pd.',
                'email' => 'budi.santoso@school.id',
                'password' => Hash::make('password'),
                'jenis_kelamin' => 'L',
                'nip' => '198501012010011001',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1985-01-01',
                'alamat' => 'Jl. Merdeka No. 10, Jakarta Selatan',
                'no_telepon' => '081234567890',
                'role' => 'guru',
                'jabatan' => 'Guru Tetap',
                'bidang_studi' => 'Matematika',
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => 'siti_aminah',
                'nama_lengkap' => 'Siti Aminah, S.Pd., M.Pd.',
                'email' => 'siti.aminah@school.id',
                'password' => Hash::make('password'),
                'jenis_kelamin' => 'P',
                'nip' => '198302152008012002',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1983-02-15',
                'alamat' => 'Jl. Asia Afrika No. 25, Bandung',
                'no_telepon' => '082345678901',
                'role' => 'guru',
                'jabatan' => 'Kepala Jurusan',
                'bidang_studi' => 'Bahasa Indonesia',
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => 'ahmad_fauzi',
                'nama_lengkap' => 'Ahmad Fauzi, S.Kom.',
                'email' => 'ahmad.fauzi@school.id',
                'password' => Hash::make('password'),
                'jenis_kelamin' => 'L',
                'nip' => '199005202015011003',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '1990-05-20',
                'alamat' => 'Jl. Darmo No. 55, Surabaya',
                'no_telepon' => '083456789012',
                'role' => 'guru',
                'jabatan' => 'Wali Kelas',
                'bidang_studi' => 'Informatika',
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => 'dewi_lestari',
                'nama_lengkap' => 'Dewi Lestari, S.Pd.',
                'email' => 'dewi.lestari@school.id',
                'password' => Hash::make('password'),
                'jenis_kelamin' => 'P',
                'nip' => '198807102012012004',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '1988-07-10',
                'alamat' => 'Jl. Malioboro No. 88, Yogyakarta',
                'no_telepon' => '084567890123',
                'role' => 'guru',
                'jabatan' => 'Guru Tetap',
                'bidang_studi' => 'Bahasa Inggris',
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => 'irwan_prasetyo',
                'nama_lengkap' => 'Irwan Prasetyo, S.Si., M.Si.',
                'email' => 'irwan.prasetyo@school.id',
                'password' => Hash::make('password'),
                'jenis_kelamin' => 'L',
                'nip' => '198203252006011005',
                'tempat_lahir' => 'Semarang',
                'tanggal_lahir' => '1982-03-25',
                'alamat' => 'Jl. Pandanaran No. 12, Semarang',
                'no_telepon' => '085678901234',
                'role' => 'guru',
                'jabatan' => 'Wakil Kepala Sekolah',
                'bidang_studi' => 'Fisika',
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => 'nina_kartika',
                'nama_lengkap' => 'Nina Kartika, S.Pd.',
                'email' => 'nina.kartika@school.id',
                'password' => Hash::make('password'),
                'jenis_kelamin' => 'P',
                'nip' => '199108302018012006',
                'tempat_lahir' => 'Medan',
                'tanggal_lahir' => '1991-08-30',
                'alamat' => 'Jl. Gajah Mada No. 76, Medan',
                'no_telepon' => '086789012345',
                'role' => 'guru',
                'jabatan' => 'Guru Honorer',
                'bidang_studi' => 'Kimia',
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => 'rahmat_hidayat',
                'nama_lengkap' => 'Rahmat Hidayat, S.Pd.',
                'email' => 'rahmat.hidayat@school.id',
                'password' => Hash::make('password'),
                'jenis_kelamin' => 'L',
                'nip' => '198610152009011007',
                'tempat_lahir' => 'Makassar',
                'tanggal_lahir' => '1986-10-15',
                'alamat' => 'Jl. Sudirman No. 45, Makassar',
                'no_telepon' => '087890123456',
                'role' => 'guru',
                'jabatan' => 'Guru Tetap',
                'bidang_studi' => 'Biologi',
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => 'wahyu_nugroho',
                'nama_lengkap' => 'Wahyu Nugroho, S.Pd.',
                'email' => 'wahyu.nugroho@school.id',
                'password' => Hash::make('password'),
                'jenis_kelamin' => 'L',
                'nip' => '197512201998011008',
                'tempat_lahir' => 'Solo',
                'tanggal_lahir' => '1975-12-20',
                'alamat' => 'Jl. Slamet Riyadi No. 100, Solo',
                'no_telepon' => '088901234567',
                'role' => 'guru',
                'jabatan' => 'Guru Senior',
                'bidang_studi' => 'Sejarah',
                'status' => 'pensiun',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('users')->insert($guru);
    }
}
